### ISSUE TITLE
virtual camera can used by other applications

### ISSUE THREAD

**Issue by hjc3613** [kaustubh-sadekar/VirtualCam#1]
hello, my friend, now I am facing one problem, I want to create an virtual camera, it process the frame captured from physical camera, and it's output  can be use by other applications like OBS. how can I do this? appreciate your answer!

**Comment by kaustubh-sadekar** [comment]
> hello, my friend, now I am facing one problem, I want to create an virtual camera, it process the frame captured from physical camera, and it's output can be use by other applications like OBS. how can I do this? appreciate your answer!

Sorry for the late response. You might have to use some python library that allows you to emulate a dummy camera. Output of VirtualCam can be merged in the pipeline after that. This way you should be able to select the output video stream processed using VirtualCam as your source camera for video call or for OBS just like you select front camera or USB camera option.

I hope this helps. I have not tried it yet. If I do I will share the code for future reference.

**Comment by kaustubh-sadekar** [comment]
Closing the issues for now.
